export const PUSH_MESSAGE = 'PUSH_MESSAGE'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'

export const FETCH_PROMPTS = 'FETCH_PROMPTS'
export const UPDATE_PROMPT = 'UPDATE_PROMPT'

export const FETCH_SCHEDULES = 'FETCH_SCHEDULES'
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE'
export const ADD_SCHEDULE = 'ADD_SCHEDULE'
